#spring:
#  application:
#    name: micro-service-one
#    
#server:
#  port: 9100
#
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:9001/eureka
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9001/eureka
      instance:
      preferIpAddress: true
      
spring:
   application:
      name: eurekaclient
      
server:
  port: 9100